"""empty message

Revision ID: 9de913306a22
Revises: 17809a473add
Create Date: 2022-08-13 08:28:55.079076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de913306a22'
down_revision = '17809a473add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'seeking_venues')
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=300), nullable=False))
    op.drop_column('venue', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_description')
    op.add_column('artist', sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
